
#' Estimate the score vector of a data matrix corresponding to the given column \code{id}.
#'
#' This function estimates the score vector of a given column \code{id} in the data matrix \code{X}. The response variable in the model is the column \code{id} of \code{X},
#' while the predictor variables are the other columns in \code{X}. Node-wise Lasso method is applied to the transformed data
#' using the decorrelating matrix \code{F_dc}. The transformed predictors are obtained by multiplying the decorrelating matrix
#' by the predictor matrix, i.e., \code{F_dc %% X[,-id]}. And the response is \code{F_dc %% X[,id]}.
#'
#' @param X A matrix data.
#' @param id Column number of \code{X}.
#' @param F_dc The decorrelating matrix used to transform on the matrix data \code{X}.
#'
#' @return
#' A score vector.
#' @export
#'
#' @examples
esti_score <- function(X,id,F_dc){
  # reference from its own paper
  # require(glmnet)
  # estimate F_dc
  Xj <- X[,id]; X_negj <- X[,-id]
  Xj_tilde <- F_dc %*% Xj; X_negj_tilde <- F_dc %*% X_negj
  cv.fit <- glmnet::cv.glmnet(X_negj_tilde,Xj_tilde,lambda.min.ratio=0.01)
  Z <- Xj_tilde - stats::predict(cv.fit,X_negj_tilde,s='lambda.min')

  tau_star <- 1.25 * nrow(X) / norm(Z,type='2')**2
  lambda_vec <- cv.fit$lambda
  bias_vec <- c();    tau2_vec <- c()
  for(lam in lambda_vec){
    z_score <- Xj_tilde - stats::predict(cv.fit,X_negj_tilde,s=lam)
    bias <- max(abs(t(X_negj_tilde) %*% z_score)) / abs(sum(Xj_tilde * z_score))
    bias_vec <- c(bias_vec,bias)
    tau2_vec <- c(tau2_vec,nrow(X) / norm(z_score,type='2')**2)
  }

  lam <- lambda_vec[which.min(bias_vec[tau2_vec <= tau_star])]
  gamma_hat <- stats::coef(cv.fit,s=lam)[-1]
  z_score <- Xj_tilde - stats::predict(cv.fit$glmnet.fit,X_negj_tilde,s=lam)
  return(as.vector(z_score))

}

#' Estimate the score matrix for a given data matrix.
#'
#' Estimate the score matrix of a data matrix using node-wise Lasso on the transformed data matrix.
#'
#' @param X A matrix data.
#' @param rho A parameter in (0,1) used to define the Trim transformation matrix.
#' @param is.parallel A logical value indicating whether to use parallel computation, default is TRUE.
#' @param core_num The number of CPU cores to use in parallel computation, default is depends on your system.
#' @param standardize A logical value indicating whether to standardize the data. Default is TRUE.
#'
#' @return
#' A list of length \code{ncol(X)}, with each element returned from \code{esti_score()} function.
#' @export
#'
#' @examples
esti_score_all <- function(X,rho=0.5,is.parallel=F,core_num = 4,standardize=TRUE){
  n <- nrow(X); p <- ncol(X)
  if(standardize){
    sd_x <- apply(X, 2, stats::sd)
    X <- scale(X,center=T,scale=sd_x)
  }

  svd.X <- svd(X)
  U <- svd.X$u; D <- svd.X$d; V <- svd.X$v

  D_lead <- dplyr::lead(D)
  K_bar <- floor(min(n,p)/2)
  K_hat <- which.max(D[1:K_bar] / D_lead[1:K_bar])

  D_tilde <- rep(1,ncol(U)); D_tilde[1:K_hat] <- 0
  F_dc <- U %*% diag(D_tilde) %*% t(U)

  if(is.parallel){
    library(foreach)
    type <- ifelse(.Platform$OS.type=='windows','PSOCK','FORK')
    core_num <- ifelse(is.null(core_num),parallel::detectCores(logical = F)-1,core_num)
    cl <- parallel::makeCluster(core_num,type)
    doParallel::registerDoParallel(cl)
    score_ls <- foreach::foreach(id = 1:p)%dopar%{
      source('./R/fun_ddlasso.R')
      sub_score<- esti_score(X,id=id,F_dc)
      sub_score
    }
    doParallel::stopImplicitCluster();
    parallel::stopCluster(cl)

  }else{
    score_ls <- ls()
    for(id in 1:p){
      sub_score <- esti_score(X,id=id,F_dc)
      score_ls[[id]] <- sub_score
    }
  }
  return(score_ls)
}


#' Infer the coefficient high dimensional linear model with latent confounder using double debiased strategy.
#'
#' This function estimates and infers the coefficients of a high-dimensional linear model with a latent confounder using the Decorrelate & Debiase method proposed by Sun, Ma, and Xia (2022).
#'
#' @references Sun, Y., Ma, L., & Xia, Y. (2022). A decorrelating and debiasing approach to simultaneous inference for high-dimensional confounded models.
#' arXiv preprint arXiv:2202.05162.
#'
#' @param X A matrix of predictor data.
#' @param Y A vector of response data.
#' @param rho A scalar correlation parameter between the residual of X and Y given the confounder Z.
#' @param is.parallel A logical value indicating whether to use parallel computation, default is TRUE.
#' @param core_num The number of CPU cores to use in parallel computation, default is depends on your system.
#' @param is.adap A logical value, if FALSE (default), the initial estimate in \code{infer_ddlasso()} uses LASSO, otherwise, adaptive LASSO is used.
#' @param score_ls A list of score vectors, generated by \code{esti_score_all()}.
#' @param standardize A logical value indicating whether to standardize the data. Default is TRUE.
#'
#' @return
#' A data frame with 5 columns. Column \code{init_coef} represents the initial estimates. Column \code{dd_coef} represents the double debiased estimate. Column \code{std}
#' represents the standard deviation of the estimates. Column \code{z_stat} represents the scaled estimates. Column \code{pvalue} represents the p-value of the estimates.
#'
#' @export
#'
#' @examples
infer_ddlasso <- function(X,Y,rho=0.5,is.parallel=F,core_num = 4,
                          is.adap=T,score_ls = NULL,standardize=TRUE){
  # method: choose lambda_j method
  n <- nrow(X); p <- ncol(X)
  if(standardize){
    sd_x <- apply(X, 2, stats::sd)
    X <- scale(X,center=T,scale=sd_x)
    Y <- Y - mean(Y)
  }else{
    sd_x <- rep(1,p)
  }

  svd.X <- svd(X)
  U <- svd.X$u; D <- svd.X$d; V <- svd.X$v

  D_lead <- dplyr::lead(D)
  K_bar <- min(floor(min(n,p)/2),20)
  K_hat <- which.max(D[1:K_bar] / D_lead[1:K_bar])

  D_tilde <- rep(1,ncol(U)); D_tilde[1:K_hat] <- 0
  # F_dc <- U %*% diag(D_tilde) %*% t(U)  # paper used
  F_dc <- diag(n) - U %*% diag(1 - D_tilde) %*% t(U)  # if rank(x)=n, it's equal

  #trimmed lasso: perform a lasso fit for trimmed F_tX and F_tY(STEP 2)
  #forms QX and QY(STEP 1)
  tau <- stats::quantile(D, rho)
  Dtilde <- pmin(D, tau) # 前面是tau，后面是自身
  F_t <- diag(n) - U %*% diag(1 - Dtilde / D) %*%  t(U)  # from Guo et.al

  Xtilde <- F_t %*% X; Ytilde <- F_t %*% Y
  # cv.fit <- cv.glmnet(x=Xtilde, y=Ytilde)

  ### Estimate the initial estimator
  if(is.adap){
    cv.fit <- glmnet::cv.glmnet(x=Xtilde, y=Ytilde,alpha=0) #
    beta_hat_init <- as.matrix((glmnet::coef.glmnet(cv.fit,s = cv.fit$lambda.min)[-1]))
    weight <- 1/abs(beta_hat_init)
    weight[weight==Inf] <-  1e4
    cv.adalasso <- glmnet::cv.glmnet(Xtilde,Ytilde,lambda.min.ratio=0.01,penalty.factor=weight)

    beta_hat_init <- as.vector(stats::coef(cv.adalasso,s='lambda.1se')[-1])
    error_vec <- Ytilde - stats::predict(cv.adalasso,Xtilde,s='lambda.1se')
    residual_init <- Y - stats::predict(cv.adalasso,X,s='lambda.1se')  # 用于bias计算中
  }else{
    # 使用sparser estimates
    cv.fit <- glmnet::cv.glmnet(x=Xtilde, y=Ytilde,lambda.min.ratio=0.01) # 固定，不使用默认
    # plot(cv.fit)

    beta_hat_init <- as.matrix(glmnet::coef.glmnet(cv.fit,s=cv.fit$lambda.1se)[-1]) # 更加稀疏，error norm更大,sigma_xi估计更大
    error_vec <- Ytilde - stats::predict(cv.fit,Xtilde,s='lambda.1se')
    # norm(beta_hat_init-coef_true,type='2')**2
    residual_init <- Y - stats::predict(cv.fit,X,s='lambda.1se')  # 用于bias计算中
  }


  # Step 7
  divisor <- sum(diag(F_t%*%F_t))
  error <- norm(error_vec,type='2')**2
  sigma_xi_hat <- (error/divisor)**0.5

  if(is.null(score_ls)){
    if(is.parallel){
      library(foreach)
      type <- ifelse(.Platform$OS.type=='windows','PSOCK','FORK')
      core_num <- ifelse(is.null(core_num),parallel::detectCores(logical = F)-1,core_num)

      cl <- parallel::makeCluster(core_num,type)
      doParallel::registerDoParallel(cl)
      coef_mat <- foreach::foreach(id = 1:p,.combine = 'rbind')%dopar%{
        source('./R/fun_ddlasso.R')
        z_score <- esti_score(X,id=id,F_dc)

        bias <- t(z_score) %*% F_dc  %*% residual_init / (t(z_score) %*% F_dc %*% X[,id])

        coef_debiased <- beta_hat_init[id] + bias

        sd_coef_id <- sigma_xi_hat / sqrt(sum(z_score**2))
        c(beta_hat_init[id],coef_debiased,sd_coef_id)
      }
      doParallel::stopImplicitCluster();
      parallel::stopCluster(cl)
      colnames(coef_mat) <- c('init_coef','dd_coef','std')

    }else{
      coef_mat <- matrix(0,nrow=p,ncol=3)
      colnames(coef_mat) <- c('init_coef','dd_coef','std')
      for(id in 1:p){
        z_score <- esti_score(X,id=id,F_dc)

        bias <- t(z_score) %*% F_dc  %*% residual_init / (t(z_score) %*% F_dc %*% X[,id])

        coef_debiased <- beta_hat_init[id] + bias

        sd_coef_id <- sigma_xi_hat / sqrt(sum(z_score**2))
        coef_mat[id,] <- c(beta_hat_init[id],coef_debiased,sd_coef_id)

      }
    }
  }else{
    if(is.parallel){
      library(foreach)
      type <- ifelse(.Platform$OS.type=='windows','PSOCK','FORK')
      core_num <- ifelse(is.null(core_num),parallel::detectCores(logical = F)-1,core_num)

      cl <- parallel::makeCluster(core_num,type)
      doParallel::registerDoParallel(cl)
      coef_mat <- foreach::foreach(id = 1:p,.combine = 'rbind')%dopar%{
        source('./R/fun_ddlasso.R')
        z_score <- score_ls[[id]]
        bias <- t(z_score) %*% F_dc  %*% residual_init / (t(z_score) %*% F_dc %*% X[,id])

        coef_debiased <- beta_hat_init[id] + bias

        sd_coef_id <- sigma_xi_hat / sqrt(sum(z_score**2))
        c(beta_hat_init[id],coef_debiased,sd_coef_id)
      }
      doParallel::stopImplicitCluster();
      parallel::stopCluster(cl)
      colnames(coef_mat) <- c('init_coef','dd_coef','std')

    }else{
      coef_mat <- matrix(0,nrow=p,ncol=3)
      colnames(coef_mat) <- c('init_coef','dd_coef','std')
      for(id in 1:p){
        z_score <- score_ls[[id]]

        bias <- t(z_score) %*% F_dc  %*% residual_init / (t(z_score) %*% F_dc %*% X[,id])

        coef_debiased <- beta_hat_init[id] + bias

        sd_coef_id <- sigma_xi_hat / sqrt(sum(z_score**2))
        coef_mat[id,] <- c(beta_hat_init[id],coef_debiased,sd_coef_id)

      }
    }
  }

  z_stat <- coef_mat[,2] / coef_mat[,3]
  pvalue <- 2*(1- stats::pnorm(abs(z_stat)))

  coef_mat <- cbind(coef_mat,z_stat,pvalue)
  coef_df <- as.data.frame(coef_mat)
  coef_df$init_coef <- coef_mat[,1] / sd_x
  coef_df$dd_coef <- coef_mat[,2] / sd_x
  coef_df$std <- coef_mat[,3] / sd_x
  return(coef_df)
}



















